spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sisima
    username: sisima
    password: SystemSima2025_

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  redis:
    host: localhost
    port: 6379

server:
  port: 8080

# Flyway
spring.flyway.enabled: true
spring.flyway.locations: classpath:db/migration
