version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sisima_postgre
    environment:
      POSTGRES_USER: sisima
      POSTGRES_PASSWORD: SystemSima2025_
      POSTGRES_DB: sisima
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: sisima_redis
    ports:
      - "6379:6379"
    networks:
      - backend

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sisima_api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sisima
  #     SPRING_DATASOURCE_USERNAME: sisima_postgre
  #     SPRING_DATASOURCE_PASSWORD: SystemSima2025_
  #     SPRING_REDIS_HOST: redis_sisima
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - backend

networks:
  backend:

volumes:
  pgdata:
